### ISSUE TITLE
SDK stopped working after v1.1.0

### ISSUE THREAD

**Issue by druiz0992** [NightfallRollup/nightfall-sdk#12]
Trying to used SDK after version v1.1.0 produces following error

```file:///home/david/iden3/tmp/nightfall-3/test/e2e/protocol/health-and-contracts.test.mjs:6
import { UserFactory } from 'nightfall-sdk';
         ^^^^^^^^^^^
SyntaxError: Named export 'UserFactory' not found. The requested module 'nightfall-sdk' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'nightfall-sdk';
const { UserFactory } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:438:15)
    at async formattedImport (/home/david/iden3/tmp/nightfall-3/node_modules/mocha/lib/nodejs/esm-utils.js:7:14)
    at async Object.exports.loadFilesAsync (/home/david/iden3/tmp/nightfall-3/node_modules/mocha/lib/nodejs/esm-utils.js:91:20)
    at async SimpleTaskDefinition.action (/home/david/iden3/tmp/nightfall-3/node_modules/hardhat/src/builtin-tasks/test.ts:128:9)
    at async Environment._runTaskDefinition (/home/david/iden3/tmp/nightfall-3/node_modules/hardhat/src/internal/core/runtime-environment.ts:308:14)
    at async Environment._runTaskDefinition (/home/david/iden3/tmp/nightfall-3/node_modules/hardhat/src/internal/core/runtime-environment.ts:308:14)
```

**Comment by imagobea** [comment]
As the title suggests, looks like the last working version is `v1.0.2` commit `74dc4cc`

Most relevant commits from `v1.1.0`

- [Fix SDK browser compatibility](https://github.com/NightfallRollup/nightfall-sdk/commit/3b68d421f573335dc8a84f4b8b4ad53c14d13103#diff-b55cdbef4907b7045f32cc5360d48d262cca5f94062e353089f189f4460039e0)

- [feature: l2 tokenisation, mint & burn](https://github.com/NightfallRollup/nightfall-sdk/commit/f2be17d86de18ad1502981c45aeed6e6445db4eb#diff-b55cdbef4907b7045f32cc5360d48d262cca5f94062e353089f189f4460039e0)

Most relevant commits from `v1.1.2`

- [fix: dist folder ignored at publish](https://github.com/NightfallRollup/nightfall-sdk/commit/819b733078203c13a0f5457fd2e201505c4137d1)

Currently investigating

**Comment by imagobea** [comment]
Narrowed down issue:

- SDK working on CJS projects (package is installable and usable), but not on ESM

I am positive that we can resolve this with @pawelgrzybek and carry on using this SDK in the future.

**Comment by imagobea** [comment]
Please refer to linked PR
